# Generated by Django 3.2.3 on 2021-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.CharField(max_length=50, verbose_name='规则添加者')),
                ('risk_level', models.PositiveIntegerField(choices=[(0, '无风险'), (1, '一般'), (2, '关注'), (3, '严重'), (4, '紧急')], default=0, verbose_name='规则等级')),
                ('input_type', models.PositiveIntegerField(choices=[(1, '批量导入'), (2, '手动添加'), (3, '自动收集')], default=2, verbose_name='导入类型')),
                ('rule_id', models.CharField(max_length=100, verbose_name='规则id')),
                ('rule_type', models.CharField(max_length=50, verbose_name='规则类型')),
                ('rule_name', models.CharField(max_length=300, verbose_name='规则名')),
                ('content', models.CharField(max_length=1000, verbose_name='规则内容')),
                ('pcap_path', models.CharField(max_length=255, verbose_name='验证规则的pcap文件')),
                ('comment', models.CharField(max_length=1000, verbose_name='用户评论')),
            ],
            options={
                'verbose_name': 'Attack',
                'verbose_name_plural': 'Attack',
            },
        ),
    ]
