# Generated by Django 3.2.3 on 2021-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='rule_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='规则名'),
        ),
    ]
