# Generated by Django 3.2.3 on 2021-05-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_attack_rule_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attack',
            options={'verbose_name': 'Attacks', 'verbose_name_plural': 'Attacks'},
        ),
        migrations.AlterModelTable(
            name='attack',
            table='attacks',
        ),
    ]
