# Generated by Django 3.2.3 on 2021-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210520_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='用户评论'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='pcap_path',
            field=models.CharField(max_length=255, null=True, verbose_name='验证规则的pcap文件'),
        ),
    ]
