# Generated by Django 3.2.3 on 2021-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210529_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='用户评论'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='pcap_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='验证规则的pcap文件'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='rule_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='规则名'),
        ),
    ]
