# Generated by Django 3.2.3 on 2021-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210529_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='risk_level',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '无风险'), (1, '一般'), (2, '关注'), (3, '严重'), (4, '紧急')], default=0, verbose_name='规则等级'),
        ),
    ]
